# Generated by Django 4.1.3 on 2022-11-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='developer_type',
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AddField(
            model_name='visit',
            name='developer_type',
            field=models.CharField(default=None, max_length=65),
        ),
    ]
