# Generated by Django 4.1.3 on 2022-11-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_user_user_developer_type_visit_developer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='developer_type',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='visit',
            name='developer_type',
            field=models.CharField(max_length=65),
        ),
    ]
