# Generated by Django 4.1.3 on 2022-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_developer_type_alter_visit_developer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='CSS', max_length=100),
            preserve_default=False,
        ),
    ]
