# Generated by Django 4.1.3 on 2022-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comentario_usuario_delete_user_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
